### ISSUE TITLE
Adding New Zealand status 

### ISSUE THREAD

**Issue by fogonwater** [dragonfly-science/new-zealand-birds#2]
I was keen to use the NZ bird data to establish whether various species are native, endemic or introduced. This data is on the bird detail pages, but the harvester doesn't currently pick this detail up.

I adapted the harvester to extract this data but wanted to make sure it's permitted before I make a pull request. The data in question is in the `New Zealand status` field of the info box (e.g. http://nzbirdsonline.org.nz/species/morepork ). Is this data okay to harvest? It looks like it based on me interpretation of the notes in `README.md` but I wanted to double-check.

**Comment by fogonwater** [comment]
Ended up making a pull request from the code. Figured it's easiest if you just take a look at what I did and decide if it's okay.

**Comment by edwardabraham** [comment]
Thanks very much for this, much appreciated! This information is fine to include (it is generic information from public sources, as opposed to original content).
